import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import assetsRouter from "./assets";
import workordersRouter from "./workorders";
import workorderPartsRouter from "./workorder_parts";
import preventiveRouter from "./preventive";
import inventoryRouter from "./inventory";
import techniciansRouter from "./technicians";
import reportsRouter from "./reports";
import notificationsRouter from "./notifications";
import sitesRouter from "./sites";
import zonesRouter from "./zones";
import assetPartsRouter from "./asset_parts";
import assetDocumentsRouter from "./asset_documents";
import subcontractorsRouter from "./subcontractors";
import telegramRouter from "./telegram";
import iotRouter from "./iot";
import erpRouter from "./erp";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(assetsRouter);
router.use(workordersRouter);
router.use(workorderPartsRouter);
router.use(preventiveRouter);
router.use(inventoryRouter);
router.use(techniciansRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(sitesRouter);
router.use(zonesRouter);
router.use(assetPartsRouter);
router.use(assetDocumentsRouter);
router.use(subcontractorsRouter);
router.use(telegramRouter);
router.use(iotRouter);
router.use(erpRouter);

export default router;
